In [1]:
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
X,y=np.arange(12).reshape((6,2)),range(6)

In [3]:
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
list(y)

[0, 1, 2, 3, 4, 5]

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [9]:
X_train

array([[10, 11],
       [ 4,  5],
       [ 8,  9],
       [ 6,  7]])

In [10]:
y_train

[5, 2, 4, 3]

In [11]:
X_test

array([[0, 1],
       [2, 3]])

In [ ]:
from sklearn.base import b